### ISSUE TITLE
New video for the testing and CI module for 2023

### ISSUE THREAD

**Issue by htwangtw** [school-brainhack/school-brainhack.github.io#128]
The video and example we have now is great for introducing the concept. 
However it is using some outdated CI service. 
@FrancoisPgm and I were thinking about making a new video to introduce
1.  `pytest`
2.  GitHub action

**Comment by htwangtw** [comment]
@FrancoisPgm are you still interested in working on this? we can set a timeline for this.

**Comment by FrancoisPgm** [comment]
yes definitely

**Comment by htwangtw** [comment]
We will check in again on the 20th of March and plan to finish the slides by then

**Comment by htwangtw** [comment]
Replaced by #185
