### ISSUE TITLE
Potentially update BIDS module with CuBIDS

### ISSUE THREAD

**Issue by clarkenj** [school-brainhack/school-brainhack.github.io#142]
https://www.sciencedirect.com/science/article/pii/S1053811922007248?via%3Dihub

**Comment by htwangtw** [comment]
I really like the idea of this project, but I am not confident with how stable it actually is.
I would suggest to actually install and run it to see how it works before endorsing it.

My impression from a glance at the code base: The software lacks coverage report. No quick start guide. The documentation for installation is quite clunky and recommend conda installation without a good reason at first glance (why do they need the JS version of bids validator?)

**Comment by clarkenj** [comment]
@htwangtw I think you used CuBIDS recently, do you think we should add it to the bids module? Or leave as is? If leaving, I will close this issue.

**Comment by htwangtw** [comment]
Looking at the open PRs and maintenance history alone I am not confident it's as stable as any other software included in Brainhack School. My advice is to leave it out.
