### ISSUE TITLE
brainhack.org/school url

### ISSUE THREAD

**Issue by pbellec** [school-brainhack/school-brainhack.github.io#152]
we should redirect school.brainhackmtl.org to the new url - as many people have the old one. 

May have to look into different urls as well.
school.brainhack.org would be ideal, because suffix like school may mess with the way hugo works.

**Comment by pbellec** [comment]
check is thread, when `baseURL` is not a base url: 
https://github.com/gohugoio/hugo/issues/4995

**Comment by pbellec** [comment]
so I solved the problem by using an organization page, which has a root base url.

school-brainhack.github.io it is!

**Comment by complexbrains** [comment]
@all-contributors please add @pbellec as a contributor for bug, content, doc, eventOrganizing, maintenance, mentoring, review, ideas, code, test, tutorial, infra, data, fundingFinding, design, financial, projectManagement, research, translation.

**Comment by complexbrains** [comment]
@pbellec as a contributor for bug, content, doc, eventOrganizing, maintenance, mentoring, review, ideas, code, test, tutorial, infra, data, fundingFinding, design, financial, projectManagement, research, translation.

**Comment by complexbrains** [comment]
@pbellec as a contributor for bug, content, doc, eventOrganizing, maintenance, mentoring, review, ideas, code, test, tutorial, infra, data, fundingFinding, design, financial, projectManagement, research, translation.

**Comment by complexbrains** [comment]
@all-contributors please add @pbellec as a contributor for bug, content, doc, eventOrganizing, maintenance, mentoring, review, ideas, code, test, tutorial, infra, data, fundingFinding, design, financial, projectManagement, research, translation.
