### ISSUE TITLE
Maintenance of DL_for_neuroimaging module

### ISSUE THREAD

**Issue by clarkenj** [school-brainhack/school-brainhack.github.io#166]
## Module to maintain
Website: https://school-brainhack.github.io/modules/dl_for_neuroimaging/  
Code: https://github.com/school-brainhack/school-brainhack.github.io/tree/main/content/en/modules/DL_for_neuroimaging

## Work to be done
Please ensure: 
- [ ] links, resources and exercises reflect the state-of-the-art 
- [ ] videos are of good quality and reflect the materials.  <br> 

If any update / re-write of the module is needed, feel free to suggest alternative material in a comment! 
If you think major changes are needed, we suggest you open an issue for new modules.

**Comment by Andjelaaaa** [comment]
Hi! I can review this module!

**Comment by clarkenj** [comment]
> Hi! I can review this module!

Great, thank you! I have assigned you.

**Comment by clarkenj** [comment]
Hi @Andjelaaaa, how are you getting on with maintenance of this module? Do you need any help? Just a reminder that we are hoping to have these done by April 21st

**Comment by Andjelaaaa** [comment]
Hi @clarkenj it will be done tomorrow with my feedback on the module!

**Comment by Andjelaaaa** [comment]
I've made a pull request for this module with minor corrections. Otherwise all links are functional!

**Comment by complexbrains** [comment]
@all-contributors please add @clarkenj for bug. please add @clarkenj for content. please add @clarkenj for doc. please add @clarkenj for eventOrganizing. please add @clarkenj for maintenance. please add @clarkenj for mentoring. please add @clarkenj for review. please add @clarkenj for ideas.

**Comment by complexbrains** [comment]
@all-contributors please add @clarkenj for bug, content, doc, eventOrganizing, maintenance, mentoring, review, ideas.
