### ISSUE TITLE
Maintenance of HPC module

### ISSUE THREAD

**Issue by clarkenj** [school-brainhack/school-brainhack.github.io#167]
## Module to maintain
Website: https://school-brainhack.github.io/modules/hpc/
Code: https://github.com/school-brainhack/school-brainhack.github.io/tree/main/content/en/modules/HPC

## Work to be done
Please ensure: 
- [ ] links, resources and exercises reflect the state-of-the-art 
- [ ] videos are of good quality and reflect the materials.  <br> 

If any update / re-write of the module is needed, feel free to suggest alternative material in a comment!
If you think major changes are needed, we suggest you open an issue for new modules.

**Comment by complexbrains** [comment]
Hi @yushiangsu Thank you so much for pointing this out. We aim to work on that to make it more generalizable for the use of any HPC clusters, although the procedures might be more or less similar across all. 

We are currently in search of a maintainer for this module. Do you think could you help us updating the module?

**Comment by yushiangsu** [comment]
I'm sorry that I have no experience on HPC, so that I have no idea what should people learn to understand the generalizable concept for using HPC clusters. Sorry that I can not provide valuable updates for this module.

**Comment by complexbrains** [comment]
Thank you @yushiangsu your comment was more than helpful already for us to realize it is missing generalizability. So we will think about it and work on that. Thank you ⭐

**Comment by thecyclingcyclopse** [comment]
I will verify the course materials for this module this week.

**Comment by clarkenj** [comment]
> I will verify the course materials for this module this week.

That's great, thank you, I have assigned you!

**Comment by thecyclingcyclopse** [comment]
> > I will verify the course materials for this module this week.
> 
> That's great, thank you, I have assigned you! For those outside Canada we were thinking of updating the module to include information the [Brainhack Cloud](https://brainhack.org/brainhack_cloud/), so students can use that. Would you be happy to add some information in?

Yes of course, I will!

**Comment by clarkenj** [comment]
Hi @thecyclingcyclopse, how are you getting on with maintenance of this module? Do you need any help? Just a reminder that we are hoping to have these done by April 21st

**Comment by thecyclingcyclopse** [comment]
@htwangtw @clarkenj 
I've added information about the Brainhack Cloud and the necessity for anyone outside Canada to apply to Brainhack Cloud.
I've posted a test application to Brainhack Cloud in order to see if we need to put up additional information or change the tutorial in any other way. Best case no more changes are required and this module is ready and this issue can be closed as solved.

**Comment by clarkenj** [comment]
hi @thecyclingcyclopse , did you hear back from Brainhack Cloud at all?

**Comment by thecyclingcyclopse** [comment]
> hi @thecyclingcyclopse , did you hear back from Brainhack Cloud at all?

Yes I did, but there is no need to change the instructions any more than already implemented. (Unless we want to add an additional sentence for the TAs regarding the creation of new users in the BHC. Do you recon that's something we should add?)

**Comment by clarkenj** [comment]
> > hi @thecyclingcyclopse , did you hear back from Brainhack Cloud at all?
> 
> Yes I did, but there is no need to change the instructions any more than already implemented. (Unless we want to add an additional sentence for the TAs regarding the creation of new users in the BHC. Do you recon that's something we should add?)

Fantastic, thank you so much @thecyclingcyclopse! @me-pic went through the changes yesterday, @me-pic do you think this is something we should add? Or did you think everything was sufficient?

**Comment by me-pic** [comment]
@clarkenj LGTM
