### ISSUE TITLE
Maintenance of BIDS module

### ISSUE THREAD

**Issue by clarkenj** [school-brainhack/school-brainhack.github.io#168]
## Module to maintain
Website: https://school-brainhack.github.io/modules/bids/
Code: https://github.com/school-brainhack/school-brainhack.github.io/tree/main/content/en/modules/bids

## Work to be done
Please ensure: 
- [ ] links, resources and exercises reflect the state-of-the-art 
- [ ] videos are of good quality and reflect the materials.  <br> 

If any update / re-write of the module is needed, feel free to suggest alternative material in a comment!
If you think major changes are needed, we suggest you open an issue for new modules.

**Comment by valosekj** [comment]
I can verify this one!

**Comment by clarkenj** [comment]
> I can verify this one!

Great, thank you! I have assigned you. Also, [#142](https://github.com/school-brainhack/school-brainhack.github.io/issues/142) is relevant, see what you think.

**Comment by clarkenj** [comment]
Hi @valosekj, how are you getting on with maintenance of this module? Do you need any help? Just a reminder that we are hoping to have these done by April 21st

**Comment by valosekj** [comment]
> Hi @valosekj, how are you getting on with maintenance of this module? Do you need any help? Just a reminder that we are hoping to have these done by April 21st

I am aware of the deadline. I am working on that! I will finish tomorrow. 

But I am not sure if I can also handle [#142](https://github.com/school-brainhack/school-brainhack.github.io/issues/142) -- I am not familiar with `CuBIDS`.

**Comment by valosekj** [comment]
I went through it, and everything looks good to me!

**Comment by clarkenj** [comment]
Thank you @valosekj!
