### ISSUE TITLE
Maintenance of containers module

### ISSUE THREAD

**Issue by clarkenj** [school-brainhack/school-brainhack.github.io#169]
## Module to maintain
Website: https://school-brainhack.github.io/modules/containers/
Code: https://github.com/school-brainhack/school-brainhack.github.io/tree/main/content/en/modules/containers

## Work to be done
Please ensure: 
- [ ] links, resources and exercises reflect the state-of-the-art 
- [ ] videos are of good quality and reflect the materials.  <br> 

If any update / re-write of the module is needed, feel free to suggest alternative material in a comment! 
If you think major changes are needed, we suggest you open an issue for new modules.

**Comment by thecyclingcyclopse** [comment]
I will verify the course materials for this module this week.

**Comment by clarkenj** [comment]
Hi @thecyclingcyclopse, how are you getting on with maintenance of this module? Do you need any help? Just a reminder that we are hoping to have these done by April 21st

**Comment by thecyclingcyclopse** [comment]
Containers module checked, no changes required.
