### ISSUE TITLE
Maintenance of fmri_connectivity module

### ISSUE THREAD

**Issue by clarkenj** [school-brainhack/school-brainhack.github.io#172]
## Module to maintain
Website: https://school-brainhack.github.io/modules/fmri_connectivity/
Code: https://github.com/school-brainhack/school-brainhack.github.io/tree/main/content/en/modules/fmri_connectivity

## Work to be done
Please ensure: 
- [ ] links, resources and exercises reflect the state-of-the-art 
- [ ] videos are of good quality and reflect the materials.  <br> 

If any update / re-write of the module is needed, feel free to suggest alternative material in a comment!
If you think major changes are needed, we suggest you open an issue for new modules.

**Comment by Davi1990** [comment]
I am happy to look at this module

**Comment by clarkenj** [comment]
Hi @Davi1990, how are you getting on with maintenance of this module? Do you need any help? Just a reminder that we are hoping to have these done by April 21st

**Comment by Davi1990** [comment]
Hi @clarkenj thanks for reaching out. I have been working on the PR of the new dMRI and mne module. I am gonna finish this up asap

**Comment by Davi1990** [comment]
Hi @clarkenj I just finished to review the material. Overall everything looks good, video for me is good enough and Pierre have done a very good job explaining the framework. 

I worked on updated the jupyter notebook and polish it a bit. I think it looks much better. I've just submitted a PR. 

Please let me know 

Dave
