### ISSUE TITLE
Maintenance of fmri_parcellation module

### ISSUE THREAD

**Issue by clarkenj** [school-brainhack/school-brainhack.github.io#173]
## Module to maintain
Website: https://school-brainhack.github.io/modules/fmri_parcellation/
Code: https://github.com/school-brainhack/school-brainhack.github.io/tree/main/content/en/modules/fmri_parcellation

## Work to be done
Please ensure: 
- [ ] links, resources and exercises reflect the state-of-the-art 
- [ ] videos are of good quality and reflect the materials.  <br> 

If any update / re-write of the module is needed, feel free to suggest alternative material in a comment!
If you think major changes are needed, we suggest you open an issue for new modules.

**Comment by juchiyu** [comment]
I can go through this module

**Comment by clarkenj** [comment]
> I can take this module and go through it this week.

That's great, thank you! I have assigned you.

**Comment by clarkenj** [comment]
Hi @juchiyu, how are you getting on with maintenance of this module? Do you need any help? Just a reminder that we are hoping to have these done by April 21st

**Comment by juchiyu** [comment]
> Hi @juchiyu, how are you getting on with maintenance of this module? Do you need any help? Just a reminder that we are hoping to have these done by April 21st

Hi @clarkenj, yes, I just went through the rest of the module and found one other thing missing:
- The second link in the **Exercise** section is not working.

For these three points:
- Do you know where I can find the correct slides? And can we fix the typo?
- For the missing link, should it be this one? https://nilearn.github.io/dev/modules/datasets.html

**Comment by juchiyu** [comment]
Updates: I have sent pull requests to Pierre's GitHub to update the link

**Comment by htwangtw** [comment]
Please submit all the changes in one PR for the ease of review.

**Comment by juchiyu** [comment]
Hi @clarkenj and @htwangtw, I will add that to the description and have re-submitted the PR.
Does that look good to you? Let me know if there's anything else that I can do to make the review easier.

**Comment by htwangtw** [comment]
Yes this is perfect
