### ISSUE TITLE
Maintenance of machine_learning_basics module

### ISSUE THREAD

**Issue by clarkenj** [school-brainhack/school-brainhack.github.io#177]
## Module to maintain
Website: https://school-brainhack.github.io/modules/machine_learning_basics/
Code: https://github.com/school-brainhack/school-brainhack.github.io/tree/main/content/en/modules/machine_learning_basics

## Work to be done
Please ensure: 
- [ ] links, resources and exercises reflect the state-of-the-art 
- [ ] videos are of good quality and reflect the materials.  <br> 

If any update / re-write of the module is needed, feel free to suggest alternative material in a comment!
If you think major changes are needed, we suggest you open an issue for new modules.

**Comment by sltou** [comment]
I can take this one!

**Comment by clarkenj** [comment]
> I can take this one!

Great, thank you! I have assigned you.

**Comment by clarkenj** [comment]
Hi @sltou, how are you getting on with maintenance of this module? Do you need any help? Just a reminder that we are hoping to have these done by April 21st

**Comment by clarkenj** [comment]
> Hi, I am one of TAs from Taiwan hub. Some of students and me have watched the video and done the exercises. The video and links work without any problems.

Hi @Ruo-Chi that's great, thank you! I will close it for now but we can re-open if you like @sltou, just let me know.
