### ISSUE TITLE
Maintenance of machine_learning_neuroimaging module

### ISSUE THREAD

**Issue by clarkenj** [school-brainhack/school-brainhack.github.io#178]
## Module to maintain
Website: https://school-brainhack.github.io/modules/machine_learning_neuroimaging/
Code: https://github.com/school-brainhack/school-brainhack.github.io/tree/main/content/en/modules/machine_learning_neuroimaging

## Work to be done
Please ensure: 
- [ ] links, resources and exercises reflect the state-of-the-art 
- [ ] videos are of good quality and reflect the materials.  <br> 

If any update / re-write of the module is needed, feel free to suggest alternative material in a comment!
If you think major changes are needed, we suggest you open an issue for new modules.

**Comment by me-pic** [comment]
I'll be happy to check that module ! Will work on that this week !

**Comment by thecyclingcyclopse** [comment]
I will verify the course materials for this module this week.

**Comment by htwangtw** [comment]
Just a friendly reminder to use the automatic issue closing function so we can get a good sense of things done: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by clarkenj** [comment]
> Just a friendly reminder to use the automatic issue closing function so we can get a good sense of things done: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

I was thinking we could leave them open until the modules have also been reviewed, but do you think that would get confusing?

**Comment by htwangtw** [comment]
> 



> I was thinking we could leave them open until the modules have also been reviewed, but do you think that would get confusing?

in the case of #190, it's for closing this #178
The issue won't be closed until the PR is reviewed and merge, I don't see the issue?

**Comment by clarkenj** [comment]
> > 
> 
> > I was thinking we could leave them open until the modules have also been reviewed, but do you think that would get confusing?
> 
> in the case of #190, it's for closing this #178 The issue won't be closed until the PR is reviewed and merge, I don't see the issue?

I meant the review of the module by another TA - we had discussed one person doing maintenance, and others 'testing' the module after
