### ISSUE TITLE
Maintenance of open_data module

### ISSUE THREAD

**Issue by clarkenj** [school-brainhack/school-brainhack.github.io#179]
## Module to maintain
Website: https://school-brainhack.github.io/modules/open_data/
Code: https://github.com/school-brainhack/school-brainhack.github.io/tree/main/content/en/modules/open_data

## Work to be done
Please ensure: 
- [ ] links, resources and exercises reflect the state-of-the-art 
- [ ] videos are of good quality and reflect the materials.  <br> 

If any update / re-write of the module is needed, feel free to suggest alternative material in a comment!
If you think major changes are needed, we suggest you open an issue for new modules.

**Comment by ryancyeung** [comment]
**Links, resources, and exercises:**
1. In the Jupyter Notebook, two of the chunks threw errors when I tried to run them (at least, in the binder). I've fixed both, but not sure where I should I make the pull request - the original repo (https://github.com/surchs/bhs_nilearn_example)?

**Video:**
Thought it was clear! Good quality and reflected the materials.

**Other:**
1. The github repo link at the top of the module page just links to the module page again. 
2. Minor, but there's no image in the github repo, so the module page shows a broken image icon.

**Comment by clarkenj** [comment]
This is great, thank you! For the PR, yes please make it for the original repo and hopefully Sebastian will merge it.

I'll take a look at the link and upload an image.

**Comment by clarkenj** [comment]
Plan B @ryancyeung: I have forked Sebastian's repo [here](https://github.com/school-brainhack/bhs_nilearn_example), please can you make the PR to that repo? Apologies for this! Once it's merged I can then add a new binder link, at the moment it fails to launch, possibly due to the errors you've caught. If you also wanted to upload it to binder please go ahead! Thank you!

**Comment by ryancyeung** [comment]
Sounds good! I made the PR [here](https://github.com/school-brainhack/bhs_nilearn_example/pull/1), let me know if anything looks off. I'm also happy to upload to Binder and share the link after it's merged.
