### ISSUE TITLE
Maintenance of project_management module

### ISSUE THREAD

**Issue by clarkenj** [school-brainhack/school-brainhack.github.io#181]
## Module to maintain
Website: https://school-brainhack.github.io/modules/project_management/
Code: https://github.com/school-brainhack/school-brainhack.github.io/tree/main/content/en/modules/project_management

## Work to be done
Please ensure: 
- [ ] links, resources and exercises reflect the state-of-the-art 
- [ ] videos are of good quality and reflect the materials.  <br> 

If any update / re-write of the module is needed, feel free to suggest alternative material in a comment!
If you think major changes are needed, we suggest you open an issue for new modules.

**Comment by complexbrains** [comment]
@all-contributors please add @htwangtw for bug, content, doc, eventOrganizing, maintenance, mentoring, review, ideas.
