### ISSUE TITLE
Maintenance of python_scripts module

### ISSUE THREAD

**Issue by clarkenj** [school-brainhack/school-brainhack.github.io#183]
## Module to maintain
Website: https://school-brainhack.github.io/modules/python_scripts/
Code: https://github.com/school-brainhack/school-brainhack.github.io/tree/main/content/en/modules/python_scripts

## Work to be done
Please ensure: 
- [ ] links, resources and exercises reflect the state-of-the-art 
- [ ] videos are of good quality and reflect the materials.  <br> 

If any update / re-write of the module is needed, feel free to suggest alternative material in a comment!
If you think major changes are needed, we suggest you open an issue for new modules.

**Comment by htwangtw** [comment]
This will replace #129

Things to look after:

> Some students gave some feedback on the python scripts video saying it is not super engaging and hard to relate to the exercise. Indeed the video comes from a hands on session, where the instersting part was interacting with the instructor, it doesn't fit as well as a standalone video.

@FrancoisPgm do you still have the band width to work on this?

**Comment by FrancoisPgm** [comment]
Yes, sorry for the late response, I'll update the video.

**Comment by amandalin047** [comment]
Hi, I'm one of the TAs for the Taiwan hub. Some of our students have told us that they're still a little unsure of the role `if __name__ == "__main__"` plays, so I'm wondering if it's possible to modify the module exercise a bit such that `cypher_script` gets imported into a third .py file so the difference between a script and a module is more manifested? I currently have an extended version of the exercise that I wrote a while back, which I'd be happy to share!

**Comment by FrancoisPgm** [comment]
Hi @amandalin047 yes please do share the extended version, I'll be happy to integrate it to the module.

**Comment by amandalin047** [comment]
@FrancoisPgm I've dumped the relevant files into [this repo](https://github.com/amandalin047/BHSTW_python_scripts). A brief description is documented in `README.md`. Many thanks!
