### ISSUE TITLE
Systematically change all the "check the results with <TA name>" text with something more general.

### ISSUE THREAD

**Issue by htwangtw** [school-brainhack/school-brainhack.github.io#207]
Here's the text by @complexbrains 

> If you have any questions regarding the module content please ask them in the relevant module channel on the school Discord server. If you do not have access to the server and would like to join, please send us an email at school [dot] brainhack [at] gmail [dot] com.
Follow up with your local TA(s) to validate you completed the exercises correctly.

Do a run down after resolving all the maintenance

**Comment by me-pic** [comment]
I can take care of that if you want ! @htwangtw
