### ISSUE TITLE
Add Filter/Review Features for Project Submissions

### ISSUE THREAD

**Issue by complexbrains** [school-brainhack/school-brainhack.github.io#214]
- Add hub-associated tags to filter submitted projects.
- Give TAs a triage right to comment on the issues.

**Comment by htwangtw** [comment]
@complexbrains I have created labels for all sites. Combined with the brainhackschool 2023 tag we should be all good!
As long as TAs are members, they can be tagged for review / comment on stuff.
Shall we consider this issue closed?

**Comment by complexbrains** [comment]
Perfect thank you! Closing it! 🚀
