### ISSUE TITLE
Maintenance of Git and Github module

### ISSUE THREAD

**Issue by Danirid** [school-brainhack/school-brainhack.github.io#305]
## Description:
In the information section the contact email is written as: school [dot] brainhack [at] gmail [dot] com. instead of school.brainhack@gmail.com

**Comment by htwangtw** [comment]
hey @Danirid can you put in a pull request for this?

**Comment by Danirid** [comment]
I did a pull request but Isil removed it because she told me it was made this way to prevent bots from finding the email address. So I’m just going to remove the issue.

**Comment by Danirid** [comment]
Solved
