### ISSUE TITLE
Update module list

### ISSUE THREAD

**Issue by Danirid** [school-brainhack/school-brainhack.github.io#319]
In the "weeks" tabs, the available modules should be updated because new modules were added: "Spinal cord module"

**Comment by Danirid** [comment]
Which week ( week 1 to 4) should the INTRODUCTION TO SPINAL CORD MRI ANALYSIS  module be added? I was thinking of week 2 because this is where we introduce a lot of the introduction concepts.

**Comment by complexbrains** [comment]
Agreed!

**Comment by valosekj** [comment]
I believe this was done in https://github.com/school-brainhack/school-brainhack.github.io/pull/322.
