### ISSUE TITLE
Maintenance of Working with MNE-Python and EEG-BIDS module

### ISSUE THREAD

**Issue by Ruo-Chi** [school-brainhack/school-brainhack.github.io#324]
## Module to maintain
Website: https://school-brainhack.github.io/modules/mne_python/<br> 
Code: https://github.com/school-brainhack/school-brainhack.github.io/tree/main/content/en/modules/mne_python

## Work to be done
Please ensure: 
- [x] links, resources and exercises reflect the state-of-the-art 
- [x] videos are of good quality and reflect the materials.  <br> 
@htwangtw

**Comment by htwangtw** [comment]
Close as no issues were reported
